// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// This file is unused now as we removed Firebase dependencies
// Original implementation preserved for future reference

/*
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPj85wf9FGMAbqKtrS4jdehnqAlo02o1A',
    appId: '1:440349438432:web:052d2a3e6fc5faeab6bb85',
    messagingSenderId: '440349438432',
    projectId: 'rms-app-dd875',
    authDomain: 'rms-app-dd875.firebaseapp.com',
    storageBucket: 'rms-app-dd875.firebasestorage.app',
    measurementId: 'G-STQVYXXD16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGK0zCqyLnuIHed0IWacsxKdC9QpQQxOY',
    appId: '1:440349438432:android:e5d9773786e5ccfdb6bb85',
    messagingSenderId: '440349438432',
    projectId: 'rms-app-dd875',
    storageBucket: 'rms-app-dd875.firebasestorage.app',
  );
}
*/
