name: platter_core
description: Shared core utilities, models, and networking for Platter apps.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  logger: ^2.5.0
  flutter_secure_storage: ^9.0.0
  json_annotation: ^4.8.1
  cloud_firestore: ^6.1.2
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.10.5
  json_serializable: ^6.12.0
