#!/bin/bash
# Response Guard - Generate LLM Context
# Creates token-optimized markdown for supervisor LLM

set -e

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$ROOT_DIR/output"
CONTRACTS_DIR="$ROOT_DIR/contracts"

# Session-aware file paths
LATEST_LINK="$OUTPUT_DIR/latest_session.json"
SESSION_META="$OUTPUT_DIR/session_meta.json"
LOG_FILE="$OUTPUT_DIR/raw_logs.json"  # Fallback for backward compatibility

# Output files (timestamped)
CONTEXT_TIMESTAMP=$(date +"%Y%m%d_%H%M%S")
CONTEXT_FILE="$OUTPUT_DIR/llm_context_${CONTEXT_TIMESTAMP}.md"
LATEST_CONTEXT="$OUTPUT_DIR/llm_context.md"
ANOMALIES_FILE="$OUTPUT_DIR/anomalies.json"

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
CYAN='\033[0;36m'
NC='\033[0m'

echo -e "${GREEN}📝 Response Guard - Generate LLM Context${NC}"
echo "=========================================="

# Determine which log file to use
FLUTTER_WEB_LOG="$OUTPUT_DIR/latest_flutter_web.json"

if [ -f "$LATEST_LINK" ]; then
    # Use the symlinked latest session
    ACTIVE_LOG="$LATEST_LINK"
    SESSION_ID=$(cat "$SESSION_META" 2>/dev/null | grep -o '"currentSessionId": "[^"]*"' | cut -d'"' -f4 || echo "unknown")
    echo -e "Using session: ${CYAN}$SESSION_ID${NC}"
elif [ -f "$FLUTTER_WEB_LOG" ]; then
    # Use Flutter web logs
    ACTIVE_LOG="$FLUTTER_WEB_LOG"
    SESSION_ID=$(cat "$SESSION_META" 2>/dev/null | grep -o '"flutterWebSessionId": "[^"]*"' | cut -d'"' -f4 || echo "flutter_web")
    echo -e "Using Flutter web session: ${CYAN}$SESSION_ID${NC}"
elif [ -f "$LOG_FILE" ]; then
    # Fallback to legacy file
    ACTIVE_LOG="$LOG_FILE"
    SESSION_ID="legacy"
    echo -e "${YELLOW}Using legacy log file (no session ID)${NC}"
else
    echo -e "${RED}Error: No logs found.${NC}"
    echo "Run ./capture_logs.sh or ./capture_flutter_web.sh first to capture logs"
    exit 1
fi


# Count log entries
LOG_COUNT=$(wc -l < "$ACTIVE_LOG" | tr -d ' ')
echo "Processing $LOG_COUNT log entries..."

# Start generating context file
cat > "$CONTEXT_FILE" << EOF
# Response Monitor Session: $SESSION_ID

> Auto-generated by Response Guard. Token-optimized for LLM consumption.
> Generated at: $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## Session Summary

- **Session ID:** $SESSION_ID
- **Log entries captured:** $LOG_COUNT
- **Context generated:** $(date -u +"%Y-%m-%dT%H:%M:%SZ")

## API Calls This Session

| # | Endpoint | Type | Status |
|---|----------|------|--------|
EOF

# Parse logs and extract API calls
API_COUNT=0
while IFS= read -r line; do
    # Extract endpoint from log
    if echo "$line" | grep -qE "(⬆️|Sending request to)"; then
        API_COUNT=$((API_COUNT + 1))
        # Try to extract endpoint name
        endpoint=$(echo "$line" | grep -oE "(cart-|table-|menu-|order-)[a-zA-Z]+" | head -1 || echo "unknown")
        echo "| $API_COUNT | \`$endpoint\` | request | ⬆️ |" >> "$CONTEXT_FILE"
    elif echo "$line" | grep -qE "(⬇️|Response received)"; then
        # Try to extract status
        status=$(echo "$line" | grep -oE "Status: [0-9]+" | grep -oE "[0-9]+" || echo "?")
        echo "| - | - | response | $status |" >> "$CONTEXT_FILE"
    fi
done < <(jq -r '.log' "$ACTIVE_LOG" 2>/dev/null || cat "$ACTIVE_LOG")

# Add anomalies section
cat >> "$CONTEXT_FILE" << 'EOF'

## Anomalies Detected

EOF

# Extract errors and exceptions
ANOMALIES="[]"
ERROR_COUNT=0
while IFS= read -r line; do
    log_content=$(echo "$line" | jq -r '.log' 2>/dev/null || echo "$line")
    
    if echo "$log_content" | grep -qE "(Error|Exception|parsing_error|failed)"; then
        ERROR_COUNT=$((ERROR_COUNT + 1))
        
        # Determine severity
        if echo "$log_content" | grep -qE "(parsing_error|type.*subtype)"; then
            severity="high"
            icon="❌"
        elif echo "$log_content" | grep -qE "(not-found|invalid-argument)"; then
            severity="medium"
            icon="⚠️"
        else
            severity="low"
            icon="ℹ️"
        fi
        
        # Truncate for markdown
        truncated=$(echo "$log_content" | head -c 300)
        
        cat >> "$CONTEXT_FILE" << EOF

### $icon Anomaly #$ERROR_COUNT ($severity)

\`\`\`
$truncated
\`\`\`

EOF
    fi
done < "$ACTIVE_LOG"

if [ "$ERROR_COUNT" -eq 0 ]; then
    echo "✅ No anomalies detected in this session." >> "$CONTEXT_FILE"
fi

# Add Firebase logs section if they exist
FIREBASE_LOG="$OUTPUT_DIR/firebase_logs.json"
if [ -f "$FIREBASE_LOG" ] && [ -s "$FIREBASE_LOG" ]; then
    cat >> "$CONTEXT_FILE" << 'EOF'

## 🔥 Firebase Backend Logs

EOF
    
    FIREBASE_COUNT=0
    while IFS= read -r line; do
        log_type=$(echo "$line" | grep -o '"type": "[^"]*"' | cut -d'"' -f4 2>/dev/null || echo "")
        priority=$(echo "$line" | grep -o '"priority": "[^"]*"' | cut -d'"' -f4 2>/dev/null || echo "")
        log_content=$(echo "$line" | grep -o '"log": "[^"]*"' | cut -d'"' -f4 2>/dev/null | head -c 200 || echo "")
        
        if [ -n "$log_type" ]; then
            FIREBASE_COUNT=$((FIREBASE_COUNT + 1))
            
            case "$log_type" in
                function_start) icon="▶️" ;;
                function_end) icon="⏹️" ;;
                error) icon="❌" ;;
                warning) icon="⚠️" ;;
                http_request) icon="📨" ;;
                http_response) icon="📩" ;;
                *) icon="📝" ;;
            esac
            
            echo "- $icon **$log_type** ($priority): \`$log_content\`" >> "$CONTEXT_FILE"
        fi
    done < "$FIREBASE_LOG"
    
    if [ "$FIREBASE_COUNT" -eq 0 ]; then
        echo "No Firebase logs captured in this session." >> "$CONTEXT_FILE"
    else
        echo "" >> "$CONTEXT_FILE"
        echo "_${FIREBASE_COUNT} Firebase log entries captured._" >> "$CONTEXT_FILE"
    fi
fi

# Add recommendations section

cat >> "$CONTEXT_FILE" << 'EOF'

## Recommended Next Steps

1. Review any **high severity** anomalies above
2. Check `contracts/extracted_contracts.json` for expected response schemas
3. Reference spec files in `/backend/src-plattr/warp/complete_app_flow_html/specs/`
4. Update Flutter models if type mismatches are found

## Files to Reference

- **Contracts:** `contracts/extracted_contracts.json`
- **Session Logs:** `output/latest_session.json`
- **LLM Instructions:** `llm_instructions.md`

## Session Management

To clear logs and start fresh:
```bash
./scripts/capture_logs.sh --clear    # Clear current session
./scripts/capture_logs.sh --archive  # Archive and start fresh
./scripts/capture_logs.sh --list     # List all sessions
```

---
*Generated by Response Guard v1.1*
EOF

# Create symlink to latest context for easy access
ln -sf "$CONTEXT_FILE" "$LATEST_CONTEXT"

echo ""
echo -e "${GREEN}✅ Context generated: $CONTEXT_FILE${NC}"
echo -e "   Symlinked to: ${CYAN}$LATEST_CONTEXT${NC}"
echo ""
echo "Summary:"
echo "  - Session: $SESSION_ID"
echo "  - API calls detected: $API_COUNT"
echo "  - Anomalies found: $ERROR_COUNT"
echo ""
echo "Next steps:"
echo "  1. Review $LATEST_CONTEXT"
echo "  2. Feed to supervisor LLM"

